services:
  ollama-server:
    image: docker.io/ollama/ollama:latest
    container_name: ollama-server
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    volumes:
      - ./ollama/ollama-server:/root/.ollama
    networks:
      - ollama-docker

    # (compose v2) habilita GPU no modo "não-swarm"
    gpus:
      - driver: nvidia
        count: all
        capabilities: [gpu]

    # limites para não travar o Windows/WSL
    cpus: 2.5
    mem_limit: 8g

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    depends_on:
      - ollama-server
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false